### ISSUE TITLE
question about "react-native init AwsomeProject"

### ISSUE THREAD

**Issue by bfang711** [ahmed3mar/react-native-slick#1]
I am looking for a slick library for my existing react app. I checked your example, however it needs "react-native init AwsomeProject" at the beginning. I wonder if it is possible to just use your slider as a component instead of "init" from the very beginning. If so, how should I do it? and how should I register at the end?

thank you.

**Comment by hasibsahibzada** [comment]
@bfang711 that is just a demo on how to get started with a project from scratch. you do not have to do those steps if you already have a running project. just install the library and use it anywhere inside your components.
`$ npm i react-native-slick --save
`
and then import it into your project for usage like 
`import Slick from 'react-native-slick';
`
