### ISSUE TITLE
onTouchEnd return undefined state and context in android

### ISSUE THREAD

**Issue by anehkumar** [ahmed3mar/react-native-slick#3]
Hi, onTouchEnd return undefined state and context on android but working on ios.

**Comment by ahmed3mar** [comment]
Sorry for late,
It's react native issue https://github.com/facebook/react-native/issues/9439

But i can confirm
1. onTouchEnd is not fired on Android
2. onTouchEnd is fired on iOS
3. onTouchStart, onTouchMove, onScrollEndDrag are all fired on Android (and iOS)
